### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JulesBelveze** [JulesBelveze/BERT-sequence-classifier#5]
- [x] test models loading checkpoint
- [x] add inferer
- [x] dockerize the inferer
- [x] add documentation
- [x] add hf custom dataset
- [ ] look at continuing pretraining
